feat: integrate app with google maps api; feat: add role guard; feat:…
ksoltys99/codetain-cabs pull request #8
Opened 2023-03-14 12:13 UTC by ksoltys99

… add journey module

2023-03-16 09:27 UTC, mwaszkiewicz requested changes

2023-03-16 09:27 UTC, mwaszkiewicz commented on src/role/role.guard.ts
> +import * as jwt from 'jsonwebtoken';
I suggest to use this package https://www.npmjs.com/package/jose for handling JWT because is the certified library instead of jsonwebtoken

2023-03-16 09:27 UTC, mwaszkiewicz commented on src/user/dtos/user.dto.ts
> +  coordsLng?: string;
In my opinion coordinates should be required.

2023-03-16 09:27 UTC, mwaszkiewicz commented on src/user/user.entity.ts
> +  @Column({
Coordinates should be required, otherwise we will be not able to schedule a travel, because we will have a user in system without necessary data.

2023-03-16 09:31 UTC, mwaszkiewicz requested changes

2023-03-16 09:31 UTC, mwaszkiewicz commented on src/maps/maps.service.ts
> +        key: this.configService.get('GOOGLE_API_KEY'),
this.configService.get('GOOGLE_API_KEY'), can be defined as private variable in class, then you will only once ask config service for env variable.

2023-03-16 09:31 UTC, mwaszkiewicz commented on src/maps/maps.service.ts
> +  client: Client;
you can use JS notation of private variable # -> https://www.javascripttutorial.net/javascript-private-methods/

2023-04-19 08:51 UTC, DominikMarciniszyn approved these changes

2023-04-20 07:56 UTC, merged